version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/node:18.16"
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: commitlint
          command: npx --no-install commitlint-circle
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
