name: CI - Pull Request Closed
on:
  pull_request:
    types: [closed]

env:
  DEPLOYMENT_ROLE: ${{ secrets.STG_DEPLOYER_ROLE_ARN }}
  AWS_REGION: ap-southeast-1

jobs:
  remove-pr:
    name: remove
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3